# Generated by Django 5.2.12 on 2026-04-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
    ]
